# Generated by Django 5.2.1 on 2025-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_wrong',
            field=models.BooleanField(default=False),
        ),
    ]
