# Generated by Django 5.2.1 on 2025-05-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_word_is_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
    ]
