# Generated by Django 5.2.1 on 2025-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_word_wrong_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('business', '비즈니스'), ('travel', '여행'), ('daily', '일상생활')], max_length=20)),
                ('text', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('example', models.TextField(blank=True, null=True, verbose_name='예문')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
