# Generated by Django 5.2.1 on 2025-05-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_topicword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='topicword',
            name='example',
        ),
        migrations.AlterField(
            model_name='topicword',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.category'),
        ),
    ]
