# Generated by Django 5.2 on 2025-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_word_is_today_word_today_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicword',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
