# Generated by Django 5.2 on 2025-05-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_topicword_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicword',
            name='part_of_speech',
            field=models.CharField(blank=True, default='명사', max_length=50),
            preserve_default=False,
        ),
    ]
