# Generated by Django 5.2 on 2025-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_word_meaning_wordmeaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
    ]
