# Generated by Django 5.2 on 2025-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_word_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translated_example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
